version: "3.8"
services:
  app:
    build: .
    image: rag-chat-springboot:latest
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rag_chat_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - API_KEY=supersecretapikey
      - PORT=3000
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rag_chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
